AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for RSS Feed Processor S3 Bucket'

Parameters:
  S3BaseName:
    Type: String
    Default: ai-researcher-rss
    Description: "Base name for the S3 bucket; the final name will be ${S3BaseName}-${AWS::Region}" 

Resources:
  ArticleContentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${S3BaseName}-${AWS::Region}'
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

Outputs:
  BucketName:
    Description: 'Name of the S3 bucket for article content'
    Value: !Ref ArticleContentBucket
    Export:
      Name: !Sub '${AWS::StackName}-ArticleContentBucketName'